name: push

"on":
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag-commit@latest
        with:
          latest: true
          major: true
          major-minor: true
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    environment:
      name: pypi
    needs:
      - tag
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Build Python package and upload distribution
        uses: dycw/action-uv-publish@latest
